name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Deploy
    uses: vlingo/xoom-platform/.github/workflows/build.yml@master
    secrets: inherit
    with:
      maven-build-cmd: mvn --batch-mode --update-snapshots -Pgithub-releases install -Dtest=\!SecureClientTest
